name: PyTest
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Unit Testing With Python
        uses: PrajjawalBanati/Python-actions@0.0.1
